# Console debug log output
debug: false

# Matching message keywords
messages:
  - "&e's game mode has been set to"
  # Strings starting with # will be treated as regular expressions
  # Color codes within regular expressions need to use ยง
  # The following expression matches messages containing the keyword hello
  - "#^.*hello.*$"

# Commands executed after interception
commands:
  - "say {player} {message}"