# 输出控制台调试日志
debug: false

# 匹配的消息关键字
messages:
  - "&e的游戏模式被设置为"
  # 使用 # 开头的字符串将被视为正则表达式
  # 正则表达式内的颜色代码需要使用 §
  # 下方表达式代表包含 hello 关键词的消息
  - "#^.*hello.*$"

# 拦截后执行的命令
commands:
  - "say {player} {message}"