main: com.puddingkc.MsgForward
name: MsgForward
version: 1.0.1
api-version: "1.20"
author: PuddingKC
depend: [packetevents]
commands:
  msgforward:
    permission: msgforward.admin
    aliases: [mf]
permissions:
  msgforward.admin:
    default: op